FROM ghcr.io/open-webui/open-webui:main

COPY static/custom.css /app/build/static/custom.css
COPY static/loader.js /app/build/static/loader.js
COPY static/onboarding-sidebar.js /app/build/static/onboarding-sidebar.js
